<?php
/**
 * Frontend Content Management Class
 * This Class is self contained and is used in different ways for different Sites
 *
 * @category   Web application framework
 * @package    Cliq
 * @author     Original Author <conkascom@gmail.com>
 * @copyright  2017 Webcliq
 * @license    http://www.php.net/license/3_01.txt  PHP License 3.01
 * @version    Release: 4.1.0
 * @link       http://cliqon.com
 */
class Cms 
{
	const THISCLASS = "Cms";
	private static $idioms;
	const CLIQDOC = "c_document";

	function __construct() 
	{
		global $clq;
		global $cfg;
		self::$idioms = $cfg['site']['idioms'];
	}

	/** Related to important site pages 
	 *
	 * idiomOptions()
	 * index() - default index page 
	 * content() - main page content caller
	 * 
	 *****************************************************************************************************/	

		/** Language Select widget
		 * Generates the options for a Language selector dropdown 
		 * @param - string - language code
		 * @return - string - set of select options
		 **/
		  function idiomOptions($idiom)
		  {
			global $clq; $opts = "";
			$idiom = $clq->get('idiom');
			$idioms = $clq->get('cfg')['site']['idioms'];
			foreach($idioms as $lcdcode => $lcdname) {
				$idiom == $lcdcode ? $s = ' selected="selected" ': $s = '' ;
				$opts .= '<option value="'.$lcdcode.'" '.$s.'>'.$lcdname.'</option>';
			}
			return $opts;
		  }

		/** Default Index Page content widget
		 * Creates content for an index page
		 * A URL for this would look like http://yourdomain.com/
		 * This is an example of how one might design a Method to return content to a Template
		 * You could return either an array or a string to be consumed by the template
		 * You would use this to create content for the Default Route for the default index.tpl
		 * @param - string - language code - probably the default or autogenerated
		 * @return - array or string with template content
		 **/
		  function index($idiom)
		  {
		 	// Can be a string or an array
		 	$content = "Default index page content";
		 	return $content;
		  }

		/** Content pages widget
		 * This is an example of how one might design a Method to return content to a Template
         * This Method would be used to create content for any page after the visitor has started navigating, including returning to Home or Index
         *
         * A URL for this could look like http://yourdomain.com/page/lcdcode/screen/action/
         * OR http://yourdomain.com/page/lcdcode/screen/action/subaction/?=REQUEST
         *
		 * @param - string - language code - probably the default or autogenerated
		 * @param - string - $screen - If, ElseIf,Else or a switch
		 * @param - string - $action - Or a switch
		 * @param - string - 
		 * @param - string - 
		 * (Or could use )
		 *
		 * @return - array or string with template content for each page
		 **/
		 function content($idiom, $screen, $action, $subaction, $rq)
		 {
			global $clq;
			$this->cfg = $clq->get('cfg');
			$extn = $this->cfg['site']['extension'];
			$js = ""; $content = ""; $thisvars = ['rq' => $rq, 'idiom' => $idiom];
			if($screen == 'content') {

				// Name of the Component template which will be loaded from /views/components/
				$tpl = $action.".".$extn; // Default, may be overwritten
				// Only needs a routine below if cannot be dealt with completely by the template
				switch($action) {
					case "list": // List is reserved PHP word
						$result = self::listing($idiom, $subaction, $rq);
						$thisvars = $result['vars'];
						$js = $result['js']; 
						$tpl = $subaction.".".$extn; 
					break;

					default: continue; 
				};
				$content = Q::publishTpl($tpl, $thisvars, "views/components", "cache/".$idiom);
			
			} else if($screen == 'activate') {
				// Get URL to activate a User after registration 
				$auth = $clq->resolve('Auth');
				$content = $auth->userActivate($rq);
			} else if($screen == 'index') {
				$content = self::index($idiom);
			}		
			$clq->set('js', $js);			
			return $content;		
		 }

	/** Widgets for Listing pages
	 *
	 * listing() - master calling page
	 * news()
	 * weblinks()
	 * documents()
	 * library()
	 * getListingData()
	 *****************************************************************************************************/

		/** Sub method caller 
		 *
		 * @param - string - subaction: eg weblinks, library or document
		 * @return - array - two lots of value containing template content and data plus javascript for pagescript
		 **/
		 protected static function listing($idiom, $action, $rq) {	return self::$action($rq, $idiom); }

		/* Website news widget 
		 * creates a filtered and ordered (by date) recordset of published news articles
		 * @param - array - $_Request category and search
		 * @param - string - language
		 * @return - array - containing a filtered recordset, this is consumed by template at PHP / Template level
		 **/
		 static function news(array $rq, $idiom)
		 {
			global $clq;
			$config = $clq->resolve('Config');
			$ncfg = C::cfgReadFile('views/config/news.cfg');
			$thisvars = [
				'ncfg' => $ncfg
			];
			$js = "
				console.log('".$ncfg['loadingmsg']."');
				App.".$ncfg['appcall']."(".object_encode($ncfg).");
			";
			return ['vars' => $thisvars, 'js' => $js];
		 }

		/* Website useful links widget 
		 * creates a filtered and ordered (by date) recordset of published news articles
		 * @param - array - $_Request category and search
		 * @param - string - language
		 * @return - array - containing a filtered recordset, this is consumed by template at PHP / Template level
		 **/
		 static function weblinks(array $rq, $idiom)
		 {
			global $clq;
			$config = $clq->resolve('Config');
			$ncfg = C::cfgReadFile('views/config/weblinks.cfg');
			$thisvars = [
				'ncfg' => $ncfg

			];
			$js = "
				console.log('".$ncfg['loadingmsg']."');
				App.".$ncfg['appcall']."(".object_encode($ncfg).");
			";
			return ['vars' => $thisvars, 'js' => $js];
		 }

		/* Website document widget 
		 * creates a filtered and ordered (by date) recordset of published news articles
		 * @param - array - $_Request category and search
		 * @param - string - language
		 * @return - array - containing a filtered recordset, this is consumed by template at PHP / Template level
		 **/
		 static function documents(array $rq, $idiom)
		 {
			global $clq;
			$config = $clq->resolve('Config');
			$ncfg = C::cfgReadFile('views/config/document.cfg');
			$thisvars = [

			];
			$js = "
				console.log('".$ncfg['loadingmsg']."');
				App.".$ncfg['appcall']."(".object_encode($ncfg).");
			";
			return ['vars' => $thisvars, 'js' => $js];
		 }

		/* Website library widget
		 * creates a filtered and ordered (by date) recordset of published news articles
		 * @param - array - $_Request category and search
		 * @param - string - language
		 * @return - array - containing a filtered recordset, this is consumed by template at PHP / Template level
		 **/
		 static function library(array $rq, $idiom)
		 {
			global $clq;
			$config = $clq->resolve('Config');
			$ncfg = C::cfgReadFile('views/config/library.cfg');
			
			$thisvars = [
				'ncfg' => $ncfg
			];
			$js = "
				console.log('".$ncfg['loadingmsg']."');
				App.".$ncfg['appcall']."(".object_encode($ncfg).");
			";
			return ['vars' => $thisvars, 'js' => $js];
		 }

		/** Load listings data
		 * creates a filtered and ordered recordset of published or active content
		 * @param - array - arguments for the method
		 * @return - array - recordset
		 **/
		 protected static function getListingData($vars)
		 {

    		$method = self::THISCLASS.'->'.__FUNCTION__.'()';
            try {
				global $clq;
				$db = $clq->resolve('Db');
				$config = $clq->resolve('Config');
				$dcfg = C::cfgReadFile('views/config/'.$vars['tabletype'].'.cfg');

				// Set process variables
				$sql = ""; $total = 0; $offset = 0; $limit = 0; $rawrs = []; $rows = [];  $search = []; $rq = $vars['rq'];

				// Build the Query
				$sql = ""; $params = []; $where = "";
				$sql .= "SELECT * FROM ".$vars['table'];	

				// Add Tabletype as a where
				if($vars['tabletype'] != '') {
					$where .= "c_type = ?";
					$params[0] = $vars['tabletype'];
				};

				// Is Search set ?
				if(array_key_exists('search', $rq)) {if($rq['search'] != '') {
					$searches = explode(',', $rq['search']);
					foreach($searches as $t => $item) {
						$e = explode('|', $item);
						$search[$e[0]] = $e[1];
					}
				}};

				// More searches if search array has elements
				if(count($search) > 0) {
					foreach($search as $s => $w) {
						$params[] = '%'.$w.'%';
						if($where != '') {
							$where .= ' AND ';
						};
						$where .= $s." COLLATE latin1_swedish_ci LIKE ? ";
					}
				};

				if($where != '') {$sql .= " WHERE ".$where;};

				// Run query at this point to get total number of records
				$recs = R::getAll($sql, $params); 
				$total = count($recs); 

				// And add Limit by
				$offset = (int)$rq['offset']; // Reads 10
				$limit = (int)$rq['limit'];	// also reads 10
				$start = $offset;
				
				// If total number of records 
				if($total < $limit) {
					$start = 0;
					$limit = $total;
				}

				// Start creating all the edge cases here
				if(+$total > 0) {		

					$sql .= ' LIMIT '.$start.', '.$limit;
					
					// Finally Run the Query
					$rawrs = R::getAll($sql, $params); 
					$rs = D::extractAndMergeRecordset($rawrs);

					// Order and Sort by goes here

					// Now format the records
					for($r = 0; $r < count($rs); $r++) {		
						foreach($dcfg['columns'] as $f => $prop) {
							$rows[$r][$f] = Q::formatCell(
								$f, // fieldname
								$rs[$r], // row
								$prop, // properties of the field
								$vars['table'], // table from which record is derived
								$rs[$r]['id'] // row id
							);
						} 
					};	

				}; 	

				return [
					'total' => $total, 
					'rows' => $rows,
					'offset' => $offset,
					'limit' => $limit,	
					'search' => $params,			
					'sql' => $sql,
					'vars' => $vars
				];
            } catch (Exception $e) {
                return [
					'total' => $total, 
					'rows' => $rows,
					'offset' => $offset,
					'limit' => $limit,	
					'search' => $params,			
					'sql' => $sql,
					'message' => $e->getMessage()
                ];
            } 
		 }

	/** CMS API Calls 
	 * where CMS.Php acts like an API Service
	 *
	 * - loadlistingdata()
	 *
	 *****************************************************************************************************/

		/** Post Form to activate a User after registration
		 * @param - array of variables
		 * @return - array of message and content
		 **/
		function loadlistingdata($vars)
		{
			return [
				'content' => self::getListingData($vars),
				'callBack' => ""
			];
		}

		function isunique($vars)
		{
			global $clq; $db = $clq->resolve('Db');
			return [
				'content' => $db->isUnique($vars),
				'callBack' => ""
			];
		}

	/** Blog  
	 * 
	 * getblog() - 
	 * getblogdata()
	 * getblogpageform()
	 * getblogview()
	 *
	 **************************************** Blog Methods *******************************************************************/	

		function getblog($vars)
		{
			global $clq; $blog = $clq->resolve('Blog');
			return [
				'content' => $blog->displayBlog($vars),
				'callBack' => ""
			];			
		}	

		function getblogdata($vars)
		{
			global $clq; $db = $clq->resolve('Db'); $blog = $clq->resolve('Blog');
			return [
				'content' => $blog->getBlogData($vars),
				'callBack' => ""
			];		
		}

		function getblogpageform($vars)
		{
			global $clq; $db = $clq->resolve('Db'); $blog = $clq->resolve('Blog');
			return [
				'content' => $blog->getBlogForm($vars),
				'callBack' => ""
			];		
		}

		function getblogview($vars)
		{
			global $clq; $db = $clq->resolve('Db'); $blog = $clq->resolve('Blog');
			return [
				'content' => $blog->blogView($vars),
				'callBack' => ""
			];					
		}

	/** Publish various pages for the Blog system
	 * 
	 * getweblinks()
	 * getlibrary()
	 * getdocument()
	 *
	 * @parms - array - usual variables
	 * @return - array of HTML from rendered template and other datas
	 *****************************************************************************************************/

		function getweblinks($vars)
		{
            $method = self::THISCLASS.'->'.__FUNCTION__.'()';
            try {

                global $clq;
                $rq = $vars['rq'];
                $idiom = $vars['idiom'];
                $table = $vars['table'];
                $tabletype = $vars['tabletype'];
                $this->cfg = $clq->get('cfg');
                $extn = $this->cfg['site']['extension'];
                $thisvars = ['rq' => $rq, 'idiom' => $idiom, 'idioms' => $clq->get('idioms'), 'viewpath' => $clq->get('rootpath').'views/'];
                $tpl = $rq['template'].".".$extn;
                $content = Q::publishTpl($tpl, $thisvars, "views/components", "cache/".$idiom);

                $sql = "SELECT * FROM ".$table." WHERE c_type = ? ORDER BY c_reference";
                $rawset = R::getAll($sql, [$tabletype]); 

                $db = $clq->resolve('Db');
                $rs = D::extractAndMergeRecordset($rawset);

                for($r = 0; $r < count($rs); $r++) {
                    $rs[$r]['d_date'] = Q::dbDate($rs[$r]['d_date']);
                }          

                if(!is_array($rs)) {
                    throw new Exception("No recordset as an array: ".$rs);
                } 

                $js = "
                    console.log('Blog data loaded');
                "; 

                $clq->set('js', $js);       

				return [
					'content' => ['flag' => 'Ok', 'msg' => $content, 'data' => $rs],
					'callBack' => ""
				];	                

            } catch(Exception $e) {
                $err = [
                    'method' => $method,
                    'errmsg' => $e->getMessage(),
                    'vars' => $vars,
                ];
                L::cLog($err);
				return [
					'content' => ['flag' => 'NotOk', 'msg' => $e->getMessage()],
					'callBack' => ""
				];	
            } 
		}	

		function getlibrary($vars)
		{
			global $clq;


			return [
				'content' => $content,
				'callBack' => ""
			];		
		}		

	/** User Management  
	 * 
	 * login() - administration login
	 * logout() - administration logout
	 * 
	 * getuserlogin() - display user login form from component template
	 * getuserregister() - display registration form from component template
	 * postuser() - post user registration form
	 * 
	 * viewuser()
	 * deleteuser()
	 **************************************** User Management ***************************************************************/	

		function login($vars)
		{
			// table == dbuser, tabletype == "", $rq == username, password
			global $clq;
			$auth = $clq->resolve('Auth');
			return [
				'content' => $auth->login($vars['rq']),
				'callBack' => ""
			];				
		}

		/** Logout 
		 * @param - Request string
		 * @return - Template and initial data
		 **/
		function logout($vars)
		{
			global $clq;
			$auth = $clq->resolve('Auth');
			return [
				'content' => $auth->logout(),
				'callBack' => ""
			];	
		}

		/** Get Users in a table - not all users but distinguished by tabletype
		 * @param - Request string
		 * @return - Template content and initial data
		 **/
		function getusers($vars)
		{
			global $clq;
			$auth = $clq->resolve('Auth');
			$authex = $clq->resolve('Authextended');
			$result = [
				'content' => $authex->displayUsers($vars),
				'callBack' => ""
			];
			return $result;
		}

		/** Get Login form with Register and Forgot password buttons 
		 * @param - array of variables
		 * @return - array of message and content
		 **/
		function getuserlogin($vars)
		{
			global $clq;
			$auth = $clq->resolve('Auth');
			$authex = $clq->resolve('Authextended');
			$result = [
				'content' => $authex->displayLogin($vars),
				'callBack' => ""
			];
			return $result;
		}		

		function getuserregister($vars)
		{
			global $clq;
			$auth = $clq->resolve('Auth');
			$authex = $clq->resolve('Authextended');
			$result = [
				'content' => $authex->displayRegister($vars),
				'callBack' => ""
			];
			return $result;
		}	

		function postuser($vars)
		{
			global $clq;
			$auth = $clq->resolve('Auth');
			$authex = $clq->resolve('Authextended');
			$result = [
				'content' => $authex->userRegister($vars),
				'callBack' => ""
			];
			return $result;			
		}

		/** Change Password
		 * @param - array of variables
		 * @return - array of message and content
		 **/
		function changepassword($vars)
		{
			global $clq;
			$auth = $clq->resolve('Auth');
			$authex = $clq->resolve('Authextended');
			return [
				'content' => $authex->changeUserPassword($vars),
				'callBack' => ""
			];
		}

		/** Reset or Lost Password
		 * @param - array of variables
		 * @return - array of message and content
		 **/
		function forgottenpassword($vars)
		{
			global $clq;
			$auth = $clq->resolve('Auth');
			$authex = $clq->resolve('Authextended');
			return [
				'content' => $authex->forgotPassword($vars),
				'callBack' => ""
			];
		}

		/** Reset password after request to reset
		 * @param - array of variables
		 * @return - array of message and content
		 **/
		function resetpassword($vars)
		{
			global $clq;
			$auth = $clq->resolve('Auth');
			$authex = $clq->resolve('Authextended');
			return [
				'content' => $authex->identifyUser($vars),
				'callBack' => ""
			];
		}

		/** Do Change Password
		 * @param - array of variables
		 * @return - array of message and content
		 **/
		function dochangepassword($vars)
		{
			global $clq;
			$auth = $clq->resolve('Auth');
			return [
				'content' => $auth->changeUserPassword($vars),
				'callBack' => ""
			];
		}		

		/** Deactivate User and Resend Activation to email address
		 * @param - array of variables
		 * @return - array of message and content
		 **/
		function senduseractivation($vars)
		{
			global $clq;
			$auth = $clq->resolve('Auth');
			$authex = $clq->resolve('Authextended');
			return [
				'content' => $authex->sendUserActivate($vars),
				'callBack' => ""
			];
		}	

		function changeuserstatus($vars)
		{
			global $clq;
			$auth = $clq->resolve('Auth');
			$authex = $clq->resolve('Authextended');
			return [
				'content' => $authex->changeUserElement($vars),
				'callBack' => ""
			];
		}

		function dochangeuserstatus($vars)
		{
			global $clq;
			$auth = $clq->resolve('Auth');
			$authex = $clq->resolve('Authextended');
			return [
				'content' => $authex->doChangeStatus($vars),
				'callBack' => ""
			];
		}

		/**
		 * View User
		 * @param - array of variables
		 * @return - array of message and content
		 **/
		function viewuser($vars)
		{
			global $clq;
			$auth = $clq->resolve('Auth');
			$authex = $clq->resolve('Authextended');
			return [
				'content' => $authex->userProfile($vars),
				'callBack' => ""
			];
		}

		/**
		 * Delete User from dbusers after validation is completed
		 * @param - array of variables
		 * @return - array of message and content
		 **/
		function deleteuser($vars)
		{
			global $clq;
			$auth = $clq->resolve('Auth');
			$authex = $clq->resolve('Authextended');
			return [
				'content' => $authex->doDeleteUser($vars),
				'callBack' => ""
			];
		}

} // Class Ends

